In [2]:
import gmaps
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
import time

In [48]:
housing_data = pd.read_csv('Rent_Price__LA_.csv')

In [49]:
#housing2010_df = pd.get_csv
housing_data

,Policy Area,Dataset,Variable,Year,Amount,Tract,Tract Number,Neighborhood,GEOID,Location,Row ID,Date
0,Housing & Real Estate,Rent Price,Median Rent Price,2010,1044.0,"Census Tract 1011.10, Los Angeles County, Cali...",101110,Tujunga,1400000US06037101110,"(34.2595555, -118.293602)",Median_Rent_Price_2010_1400000US06037101110,01/01/2010
1,Housing & Real Estate,Rent Price,Median Rent Price,2010,1370.0,"Census Tract 1011.22, Los Angeles County, Cali...",101122,Tujunga,1400000US06037101122,"(34.267357, -118.29024)",Median_Rent_Price_2010_1400000US06037101122,01/01/2010
2,Housing & Real Estate,Rent Price,Median Rent Price,2010,1113.0,"Census Tract 1012.10, Los Angeles County, Cali...",101210,Tujunga,1400000US06037101210,"(34.251998, -118.2926875)",Median_Rent_Price_2010_1400000US06037101210,01/01/2010
3,Housing & Real Estate,Rent Price,Median Rent Price,2010,899.0,"Census Tract 1012.20, Los Angeles County, Cali...",101220,Tujunga,1400000US06037101220,"(34.2511895, -118.281014)",Median_Rent_Price_2010_1400000US06037101220,01/01/2010
4,Housing & Real Estate,Rent Price,Median Rent Price,2010,1211.0,"Census Tract 1013, Los Angeles County, California",101300,Tujunga,1400000US06037101300,"(34.2455945, -118.271731)",Median_Rent_Price_2010_1400000US06037101300,01/01/2010
5,Housing & Real Estate,Rent Price,Median Rent Price,2010,1196.0,"Census Tract 1014, Los Angeles County, California",101400,Tujunga,1400000US06037101400,"(34.244255, -118.296428)",Median_Rent_Price_2010_1400000US06037101400,01/01/2010
6,Housing & Real Estate,Rent Price,Median Rent Price,2010,1101.0,"Census Tract 1021.03, Los Angeles County, Cali...",102103,Shadow Hills,1400000US06037102103,"(34.224155, -118.354339)",Median_Rent_Price_2010_1400000US06037102103,01/01/2010
7,Housing & Real Estate,Rent Price,Median Rent Price,2010,2000.0,"Census Tract 1021.04, Los Angeles County, Cali...",102104,Shadow Hills,1400000US06037102104,"(34.216189, -118.3456235)",Median_Rent_Price_2010_1400000US06037102104,01/01/2010
8,Housing & Real Estate,Rent Price,Median Rent Price,2010,1058.0,"Census Tract 1021.05, Los Angeles County, Cali...",102105,Sun Valley,1400000US06037102105,"(34.210852, -118.3480495)",Median_Rent_Price_2010_1400000US06037102105,01/01/2010
9,Housing & Real Estate,Rent Price,Median Rent Price,2010,629.0,"Census Tract 1021.07, Los Angeles County, Cali...",102107,Shadow Hills,1400000US06037102107,"(34.2412955, -118.3292705)",Median_Rent_Price_2010_1400000US06037102107,01/01/2010
10,Housing & Real Estate,Rent Price,Median Rent Price,2010,2000.0,"Census Tract 1031.01, Los Angeles County, Cali...",103101,Sunland,1400000US06037103101,"(34.274431, -118.30714)",Median_Rent_Price_2010_1400000US06037103101,01/01/2010
11,Housing & Real Estate,Rent Price,Median Rent Price,2010,1134.0,"Census Tract 1031.02, Los Angeles County, Cali...",103102,Sunland,1400000US06037103102,"(34.262834, -118.30683)",Median_Rent_Price_2010_1400000US06037103102,01/01/2010
12,Housing & Real Estate,Rent Price,Median Rent Price,2010,994.0,"Census Tract 1032, Los Angeles County, California",103200,Lake View Terrace,1400000US06037103200,"(34.2745565, -118.3439025)",Median_Rent_Price_2010_1400000US06037103200,01/01/2010
13,Housing & Real Estate,Rent Price,Median Rent Price,2010,1838.0,"Census Tract 1033, Los Angeles County, California",103300,Shadow Hills,1400000US06037103300,"(34.255439, -118.3527775)",Median_Rent_Price_2010_1400000US06037103300,01/01/2010
14,Housing & Real Estate,Rent Price,Median Rent Price,2010,1047.0,"Census Tract 1034, Los Angeles County, California",103400,Sunland,1400000US06037103400,"(34.253933, -118.3147245)",Median_Rent_Price_2010_1400000US06037103400,01/01/2010
15,Housing & Real Estate,Rent Price,Median Rent Price,2010,1488.0,"Census Tract 1041.03, Los Angeles County, Cali...",104103,Lake View Terrace,1400000US06037104103,"(34.2819045, -118.3918905)",Median_Rent_Price_2010_1400000US06037104103,01/01/2010
16,Housing & Real Estate,Rent Price,Median Rent Price,2010,789.0,"Census Tract 1041.05, Los Angeles County, Cali...",104105,Pacoima,1400000US06037104105,"(34.276146, -118.404645)",Median_Rent_Price_2010_1400000US06037104105,01/01/2010
17,Housing & Real Estate,Rent Price,Median Rent Price,2010,1140.0,"Census Tract 1041.08, Los Angeles County, Cali...",104108,Pacoima,1400000US06037104108,"(34.271671, -118.397614)",Median_Rent_Price_2010_1400000US06037104108,01/01/2010
18,Housing & Real Estate,Rent Price,Median Rent Price,2010,1154.0,"Census Tract 1041.24, Los Angeles County, Cali...",104124,Lopez/Kagel Canyons,1400000US06037104124,"(34.287866, -118.376208)",Median_Rent_Price_2010_1400000US06037104124,01/01/2010
19,Housing & Real Estate,Rent Price,Median Rent Price,2010,826.0,"Census Tract 1042.01, Los Angeles County, Cali...",104201,Pacoima,1400000US06037104201,"(34.2867415, -118.4160805)",Median_Rent_Price_2010_1400000US06037104201,01/01/2010
20,Housing & Real Estate,Rent Price,Median Rent Price,2010,1009.0,"Census Tract 1042.03, Los Angeles County, Cali...",104203,Pacoima,1400000US06037104203,"(34.279058, -118.411554)",Median_Rent_Price_2010_1400000US06037104203,01/01/2010
21,Housing & Real Estate,Rent Price,Median Rent Price,2010,1154.0,"Census Tract 1042.04, Los Angeles County, Cali...",104204,Lake View Terrace,1400000US06037104204,"(34.2886315, -118.396898)",Median_Rent_Price_2010_1400000US06037104204,01/01/2010
22,Housing & Real Estate,Rent Price,Median Rent Price,2010,1531.0,"Census Tract 1043.10, Los Angeles County, Cali...",104310,Pacoima,1400000US06037104310,"(34.2762555, -118.4293915)",Median_Rent_Price_2010_1400000US06037104310,01/01/2010
23,Housing & Real Estate,Rent Price,Median Rent Price,2010,1138.0,"Census Tract 1043.20, Los Angeles County, Cali...",104320,Pacoima,1400000US06037104320,"(34.27316, -118.4202235)",Median_Rent_Price_2010_1400000US06037104320,01/01/2010
24,Housing & Real Estate,Rent Price,Median Rent Price,2010,813.0,"Census Tract 1044.01, Los Angeles County, Cali...",104401,Pacoima,1400000US06037104401,"(34.2670615, -118.433071)",Median_Rent_Price_2010_1400000US06037104401,01/01/2010
25,Housing & Real Estate,Rent Price,Median Rent Price,2010,1176.0,"Census Tract 1044.03, Los Angeles County, Cali...",104403,Pacoima,1400000US06037104403,"(34.2589085, -118.4345385)",Median_Rent_Price_2010_1400000US06037104403,01/01/2010
26,Housing & Real Estate,Rent Price,Median Rent Price,2010,977.0,"Census Tract 1044.04, Los Angeles County, Cali...",104404,Pacoima,1400000US06037104404,"(34.2639205, -118.4286915)",Median_Rent_Price_2010_1400000US06037104404,01/01/2010
27,Housing & Real Estate,Rent Price,Median Rent Price,2010,1314.0,"Census Tract 1045, Los Angeles County, California",104500,Pacoima,1400000US06037104500,"(34.25551, -118.4257485)",Median_Rent_Price_2010_1400000US06037104500,01/01/2010
28,Housing & Real Estate,Rent Price,Median Rent Price,2010,1277.0,"Census Tract 1046.10, Los Angeles County, Cali...",104610,Pacoima,1400000US06037104610,"(34.2604335, -118.4189955)",Median_Rent_Price_2010_1400000US06037104610,01/01/2010
29,Housing & Real Estate,Rent Price,Median Rent Price,2010,1082.0,"Census Tract 1046.20, Los Angeles County, Cali...",104620,Pacoima,1400000US06037104620,"(34.2579045, -118.422465)",Median_Rent_Price_2010_1400000US06037104620,01/01/2010
...,...,...,...,...,...,...,...,...,...,...,...,...
16360,Housing & Real Estate,Rent Price,Median Rent Price,2016,1807.0,"Census Tract 9201.10, Los Angeles County, Cali...",920110,Santa Clarita,1400000US06037920110,"(34.446814, -118.5447345)",Median_Rent_Price_2016_1400000US06037920110,01/01/2016
16361,Housing & Real Estate,Rent Price,Median Rent Price,2016,2314.0,"Census Tract 9201.11, Los Angeles County, Cali...",920111,Santa Clarita,1400000US06037920111,"(34.451756, -118.5384995)",Median_Rent_Price_2016_1400000US06037920111,01/01/2016
16362,Housing & Real Estate,Rent Price,Median Rent Price,2016,1375.0,"Census Tract 9201.12, Los Angeles County, Cali...",920112,Santa Clarita,1400000US06037920112,"(34.435109, -118.538718)",Median_Rent_Price_2016_1400000US06037920112,01/01/2016
16363,Housing & Real Estate,Rent Price,Median Rent Price,2016,1918.0,"Census Tract 9201.14, Los Angeles County, Cali...",920114,Santa Clarita,1400000US06037920114,"(34.4320305, -118.5670465)",Median_Rent_Price_2016_1400000US06037920114,01/01/2016
16364,Housing & Real Estate,Rent Price,Median Rent Price,2016,1467.0,"Census Tract 9201.15, Los Angeles County, Cali...",920115,Santa Clarita,1400000US06037920115,"(34.428275, -118.5498565)",Median_Rent_Price_2016_1400000US06037920115,01/01/2016
16365,Housing & Real Estate,Rent Price,Median Rent Price,2016,1808.0,"Census Tract 9201.16, Los Angeles County, Cali...",920116,Castaic,1400000US06037920116,"(34.4830095, -118.6364085)",Median_Rent_Price_2016_1400000US06037920116,01/01/2016
16366,Housing & Real Estate,Rent Price,Median Rent Price,2016,2665.0,"Census Tract 9201.18, Los Angeles County, Cali...",920118,Castaic,1400000US06037920118,"(34.4585725, -118.624566)",Median_Rent_Price_2016_1400000US06037920118,01/01/2016
16367,Housing & Real Estate,Rent Price,Median Rent Price,2016,3091.0,"Census Tract 9201.19, Los Angeles County, Cali...",920119,Castaic,1400000US06037920119,"(34.4642225, -118.6428175)",Median_Rent_Price_2016_1400000US06037920119,01/01/2016
16368,Housing & Real Estate,Rent Price,Median Rent Price,2016,2089.0,"Census Tract 9203.03, Los Angeles County, Cali...",920303,Unincorporated Santa Susana Mountains,1400000US06037920303,"(34.315107, -118.605768)",Median_Rent_Price_2016_1400000US06037920303,01/01/2016
16369,Housing & Real Estate,Rent Price,Median Rent Price,2016,1280.0,"Census Tract 9203.12, Los Angeles County, Cali...",920312,Santa Clarita,1400000US06037920312,"(34.357038, -118.529646)",Median_Rent_Price_2016_1400000US06037920312,01/01/2016
16370,Housing & Real Estate,Rent Price,Median Rent Price,2016,1444.0,"Census Tract 9203.13, Los Angeles County, Cali...",920313,Santa Clarita,1400000US06037920313,"(34.3707695, -118.552617)",Median_Rent_Price_2016_1400000US06037920313,01/01/2016
16371,Housing & Real Estate,Rent Price,Median Rent Price,2016,1652.0,"Census Tract 9203.14, Los Angeles County, Cali...",920314,Santa Clarita,1400000US06037920314,"(34.4044665, -118.520954)",Median_Rent_Price_2016_1400000US06037920314,01/01/2016
16372,Housing & Real Estate,Rent Price,Median Rent Price,2016,1303.0,"Census Tract 9203.22, Los Angeles County, Cali...",920322,Santa Clarita,1400000US06037920322,"(34.3842535, -118.549422)",Median_Rent_Price_2016_1400000US06037920322,01/01/2016
16373,Housing & Real Estate,Rent Price,Median Rent Price,2016,1741.0,"Census Tract 9203.26, Los Angeles County, Cali...",920326,Unincorporated Santa Susana Mountains,1400000US06037920326,"(34.364177, -118.6077495)",Median_Rent_Price_2016_1400000US06037920326,01/01/2016
16374,Housing & Real Estate,Rent Price,Median Rent Price,2016,1911.0,"Census Tract 9203.28, Los Angeles County, Cali...",920328,Santa Clarita,1400000US06037920328,"(34.416139, -118.5715565)",Median_Rent_Price_2016_1400000US06037920328,01/01/2016
16375,Housing & Real Estate,Rent Price,Median Rent Price,2016,1785.0,"Census Tract 9203.29, Los Angeles County, Cali...",920329,Santa Clarita,1400000US06037920329,"(34.4111205, -118.5512305)",Median_Rent_Price_2016_1400000US06037920329,01/01/2016
16376,Housing & Real Estate,Rent Price,Median Rent Price,2016,1833.0,"Census Tract 9203.30, Los Angeles County, Cali...",920330,Santa Clarita,1400000US06037920330,"(34.403578, -118.5636845)",Median_Rent_Price_2016_1400000US06037920330,01/01/2016
16377,Housing & Real Estate,Rent Price,Median Rent Price,2016,1618.0,"Census Tract 9203.31, Los Angeles County, Cali...",920331,Santa Clarita,1400000US06037920331,"(34.3965195, -118.5461425)",Median_Rent_Price_2016_1400000US06037920331,01/01/2016
16378,Housing & Real Estate,Rent Price,Median Rent Price,2016,1379.0,"Census Tract 9203.32, Los Angeles County, Cali...",920332,Santa Clarita,1400000US06037920332,"(34.3818215, -118.514898)",Median_Rent_Price_2016_1400000US06037920332,01/01/2016
16379,Housing & Real Estate,Rent Price,Median Rent Price,2016,1448.0,"Census Tract 9203.34, Los Angeles County, Cali...",920334,Santa Clarita,1400000US06037920334,"(34.3872515, -118.5594415)",Median_Rent_Price_2016_1400000US06037920334,01/01/2016
16380,Housing & Real Estate,Rent Price,Median Rent Price,2016,1298.0,"Census Tract 9203.36, Los Angeles County, Cali...",920336,Santa Clarita,1400000US06037920336,"(34.385239, -118.534828)",Median_Rent_Price_2016_1400000US06037920336,01/01/2016
16381,Housing & Real Estate,Rent Price,Median Rent Price,2016,1538.0,"Census Tract 9203.37, Los Angeles County, Cali...",920337,Santa Clarita,1400000US06037920337,"(34.373884, -118.5145465)",Median_Rent_Price_2016_1400000US06037920337,01/01/2016
16382,Housing & Real Estate,Rent Price,Median Rent Price,2016,2351.0,"Census Tract 9203.38, Los Angeles County, Cali...",920338,Stevenson Ranch,1400000US06037920338,"(34.386701, -118.601166)",Median_Rent_Price_2016_1400000US06037920338,01/01/2016
16383,Housing & Real Estate,Rent Price,Median Rent Price,2016,2127.0,"Census Tract 9203.39, Los Angeles County, Cali...",920339,Unincorporated Santa Susana Mountains,1400000US06037920339,"(34.4151555, -118.6238155)",Median_Rent_Price_2016_1400000US06037920339,01/01/2016
16384,Housing & Real Estate,Rent Price,Median Rent Price,2016,2050.0,"Census Tract 9302, Los Angeles County, California",930200,Tujunga Canyons,1400000US06037930200,"(34.340966, -118.294994)",Median_Rent_Price_2016_1400000US06037930200,01/01/2016
16385,Housing & Real Estate,Rent Price,Median Rent Price,2016,1263.0,"Census Tract 9303.01, Los Angeles County, Cali...",930301,Angeles Crest,1400000US06037930301,"(34.2947535, -117.913563)",Median_Rent_Price_2016_1400000US06037930301,01/01/2016
16386,Housing & Real Estate,Rent Price,Median Rent Price,2016,975.0,"Census Tract 9800.08, Los Angeles County, Cali...",980008,Van Nuys,1400000US06037980008,"(34.207747, -118.490984)",Median_Rent_Price_2016_1400000US06037980008,01/01/2016
16387,Housing & Real Estate,Rent Price,Median Rent Price,2016,NaN,"Census Tract 9800.09, Los Angeles County, Cali...",980009,Griffith Park,1400000US06037980009,"(34.136859, -118.3012315)",Median_Rent_Price_2016_1400000US06037980009,01/01/2016
16388,Housing & Real Estate,Rent Price,Median Rent Price,2016,719.0,"Census Tract 9800.10, Los Angeles County, Cali...",980010,Elysian Park,1400000US06037980010,"(34.081932, -118.238222)",Median_Rent_Price_2016_1400000US06037980010,01/01/2016
16389,Housing & Real Estate,Rent Price,Median Rent Price,2016,960.0,"Census Tract 9800.15, Los Angeles County, Cali...",980015,Wilmington,1400000US06037980015,"(33.778611, -118.295234)",Median_Rent_Price_2016_1400000US06037980015,01/01/2016

In [5]:
housing_data.columns

Index(['Policy Area', 'Dataset', 'Variable', 'Year', 'Amount', 'Tract',
       'Tract Number', 'Neighborhood', 'GEOID', 'Location', 'Row ID', 'Date'],
      dtype='object')

In [6]:
housing_data.iloc[16389]

Policy Area                                 Housing & Real Estate
Dataset                                                Rent Price
Variable                                        Median Rent Price
Year                                                         2016
Amount                                                        960
Tract           Census Tract 9800.15, Los Angeles County, Cali...
Tract Number                                               980015
Neighborhood                                           Wilmington
GEOID                                        1400000US06037980015
Location                                 (33.778611, -118.295234)
Row ID                Median_Rent_Price_2016_1400000US06037980015
Date                                                   01/01/2016
Name: 16389, dtype: object

* Define in which columns to look for missing values.

```
>>> df.dropna(subset=['name', 'born'])
       name        toy       born
1    Batman  Batmobile 1940-04-25
```

DataFrame.rename supports two calling conventions

    *(index=index_mapper, columns=columns_mapper, ...)
    *(mapper, axis={'index', 'columns'}, ...)
```
>>> df.rename(index=str, columns={"A": "a", "C": "c"})
   a  B
0  1  4
1  2  5
2  3  6
```

In [50]:
#Create DataFrame with just 2016(most recent) data
housing_2016 = housing_data[housing_data.Date == '01/01/2016']

housing_2016 = housing_2016.dropna(subset=['Amount'])



#Reset index for new DF
housing_2016 = housing_2016.reset_index()

#Drop column created by old index
housing_2016 = housing_2016.drop('index', axis=1)

#Drop column not relevant.
housing_2016 = housing_2016.drop(['Policy Area','Year','Variable','Dataset', 'Tract', 'Row ID', 'Date', 'GEOID' ], axis=1)

#Rename column
housing_2016= housing_2016.rename(columns = {'Amount': 'Median Rent 2016'})



housing_2016
#by_neighborhood = housing_data.goupby

,Median Rent 2016,Tract Number,Neighborhood,Location
0,900.0,212305,Koreatown,"(34.056107, -118.298204)"
1,1391.0,101110,Tujunga,"(34.2595555, -118.293602)"
2,1924.0,101122,Tujunga,"(34.267357, -118.29024)"
3,1141.0,101210,Tujunga,"(34.251998, -118.2926875)"
4,1123.0,101220,Tujunga,"(34.2511895, -118.281014)"
5,2131.0,101300,Tujunga,"(34.2455945, -118.271731)"
6,1190.0,101400,Tujunga,"(34.244255, -118.296428)"
7,2095.0,102103,Shadow Hills,"(34.224155, -118.354339)"
8,2552.0,102104,Shadow Hills,"(34.216189, -118.3456235)"
9,1328.0,102105,Sun Valley,"(34.210852, -118.3480495)"
10,1163.0,102107,Shadow Hills,"(34.2412955, -118.3292705)"
11,1484.0,103101,Sunland,"(34.274431, -118.30714)"
12,1509.0,103102,Sunland,"(34.262834, -118.30683)"
13,954.0,103200,Lake View Terrace,"(34.2745565, -118.3439025)"
14,2136.0,103300,Shadow Hills,"(34.255439, -118.3527775)"
15,1452.0,103400,Sunland,"(34.253933, -118.3147245)"
16,1392.0,104103,Lake View Terrace,"(34.2819045, -118.3918905)"
17,766.0,104105,Pacoima,"(34.276146, -118.404645)"
18,1298.0,104108,Pacoima,"(34.271671, -118.397614)"
19,1490.0,104124,Lopez/Kagel Canyons,"(34.287866, -118.376208)"
20,1935.0,104201,Pacoima,"(34.2867415, -118.4160805)"
21,1239.0,104203,Pacoima,"(34.279058, -118.411554)"
22,1078.0,104204,Lake View Terrace,"(34.2886315, -118.396898)"
23,1514.0,104310,Pacoima,"(34.2762555, -118.4293915)"
24,1000.0,104320,Pacoima,"(34.27316, -118.4202235)"
25,1675.0,104401,Pacoima,"(34.2670615, -118.433071)"
26,1518.0,104403,Pacoima,"(34.2589085, -118.4345385)"
27,1356.0,104404,Pacoima,"(34.2639205, -118.4286915)"
28,1304.0,104500,Pacoima,"(34.25551, -118.4257485)"
29,1423.0,104610,Pacoima,"(34.2604335, -118.4189955)"
...,...,...,...,...
2266,1940.0,920109,Santa Clarita,"(34.456252, -118.550261)"
2267,1807.0,920110,Santa Clarita,"(34.446814, -118.5447345)"
2268,2314.0,920111,Santa Clarita,"(34.451756, -118.5384995)"
2269,1375.0,920112,Santa Clarita,"(34.435109, -118.538718)"
2270,1918.0,920114,Santa Clarita,"(34.4320305, -118.5670465)"
2271,1467.0,920115,Santa Clarita,"(34.428275, -118.5498565)"
2272,1808.0,920116,Castaic,"(34.4830095, -118.6364085)"
2273,2665.0,920118,Castaic,"(34.4585725, -118.624566)"
2274,3091.0,920119,Castaic,"(34.4642225, -118.6428175)"
2275,2089.0,920303,Unincorporated Santa Susana Mountains,"(34.315107, -118.605768)"
2276,1280.0,920312,Santa Clarita,"(34.357038, -118.529646)"
2277,1444.0,920313,Santa Clarita,"(34.3707695, -118.552617)"
2278,1652.0,920314,Santa Clarita,"(34.4044665, -118.520954)"
2279,1303.0,920322,Santa Clarita,"(34.3842535, -118.549422)"
2280,1741.0,920326,Unincorporated Santa Susana Mountains,"(34.364177, -118.6077495)"
2281,1911.0,920328,Santa Clarita,"(34.416139, -118.5715565)"
2282,1785.0,920329,Santa Clarita,"(34.4111205, -118.5512305)"
2283,1833.0,920330,Santa Clarita,"(34.403578, -118.5636845)"
2284,1618.0,920331,Santa Clarita,"(34.3965195, -118.5461425)"
2285,1379.0,920332,Santa Clarita,"(34.3818215, -118.514898)"
2286,1448.0,920334,Santa Clarita,"(34.3872515, -118.5594415)"
2287,1298.0,920336,Santa Clarita,"(34.385239, -118.534828)"
2288,1538.0,920337,Santa Clarita,"(34.373884, -118.5145465)"
2289,2351.0,920338,Stevenson Ranch,"(34.386701, -118.601166)"
2290,2127.0,920339,Unincorporated Santa Susana Mountains,"(34.4151555, -118.6238155)"
2291,2050.0,930200,Tujunga Canyons,"(34.340966, -118.294994)"
2292,1263.0,930301,Angeles Crest,"(34.2947535, -117.913563)"
2293,975.0,980008,Van Nuys,"(34.207747, -118.490984)"
2294,719.0,980010,Elysian Park,"(34.081932, -118.238222)"
2295,960.0,980015,Wilmington,"(33.778611, -118.295234)"

In [52]:
housing_2016.shape

(2296, 4)

In [53]:
#Checking that all Tract Numbers are unique
len(housing_2016['Tract Number'].unique())

2296

In [ ]:
url = 'https://maps.googleapis.com/maps/api/geocode/json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA&key=' + YOUR_API_KEY

In [19]:
tract_tozip = pd.read_csv('TRACT_ZIP_032016.csv')
tract_tozip.drop(['TRACT'], axis=1, inplace= True)

tract_tozip=tract_tozip.rename(columns={'LA_TRACT': 'Tract Number'})
tract_tozip.head()

     ZIP  Tract Number
0  91042        101110
1  91042        101122
2  91042        101210
3  91043        101210
4  91042        101220

In [14]:
tract_tozip.columns

Index(['ZIP', 'LA_TRACT'], dtype='object')

In [15]:
tract_tozip.shape

(3964, 2)

In [54]:
# housing_with_zip = housing_2016
# housing_with_zip["Zip Code"] = [ for zipcode in tract_tozip['ZIP'] if ]
housing_with_zip= housing_2016.merge(tract_tozip, how='left', on="Tract Number")
# housing_with_zip.dropna()
# for i, row in housing_with_zip.iterrows():
#     if row['ZIP'] is None:
#         print(row)
# print("Done")

In [55]:
selection = housing_with_zip.loc[housing_with_zip['ZIP'].isnull()]
selection

,Median Rent 2016,Tract Number,Neighborhood,Location,ZIP
3188,1426.0,599000,Avalon,"(33.343563, -118.3300478)",NaN
3695,1911.0,137000,Woodland Hills,"(34.167095, -118.6409615)",NaN

In [56]:
new_zip_df =housing_with_zip.dropna()
new_zip_df.ZIP = new_zip_df.ZIP.astype(int)

new_zip_df.head()

/anaconda3/envs/PythonData/lib/python3.6/site-packages/pandas/core/generic.py:4405: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

,Median Rent 2016,Tract Number,Neighborhood,Location,ZIP
0,900.0,212305,Koreatown,"(34.056107, -118.298204)",90006
1,900.0,212305,Koreatown,"(34.056107, -118.298204)",90005
2,1391.0,101110,Tujunga,"(34.2595555, -118.293602)",91042
3,1924.0,101122,Tujunga,"(34.267357, -118.29024)",91042
4,1141.0,101210,Tujunga,"(34.251998, -118.2926875)",91042

In [57]:
new_zip_df.to_csv('LA_rentmedian.csv')


DataFrame.at
* Access a single value for a row/column label pair.  

DataFrame.iloc  
* Access group of rows and columns by integer position(s).  

DataFrame.xs  
* Returns a cross-section (row(s) or column(s)) from the Series/DataFrame. 

Series.loc  
* Access group of values using labels.

In [38]:
tract_tozip.index

RangeIndex(start=0, stop=3964, step=1)

In [39]:
type(tract_tozip.iat[1,0])

numpy.int64